In [2]:
import numpy as np
import pandas as pd

In [3]:
import matplotlib.pyplot as plt
%matplotlib inline

import seaborn as sns

In [4]:
import statsmodels

In [5]:
ad = pd.read_csv("C:\\Users\\Anna\\Dropbox\\My PC (DESKTOP-8G0KC76)\\Documents\\GitHub\\DP-Mini-Project\\adni.csv")

In [6]:
ad.describe()
ad

,DIAGNOSIS,AGE,PTGENDER,PTEDUCAT,PTETHCAT,PTRACCAT,PTMARRY,ADAS11.bl,ADAS13.bl,ADASQ4.bl,...,EcogSPPlan.bl,EcogSPOrgan.bl,EcogSPDivatt.bl,EcogSPTotal.bl,ABETA.bl,TAU.bl,PTAU.bl,FDG.bl,PIB.bl,AV45.bl
0,CN,74.3,Male,16,Not Hisp/Latino,White,Married,10.67,18.67,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.369264,NaN,NaN
1,Dementia,81.3,Male,18,Not Hisp/Latino,White,Married,22.00,31.00,8.0,...,NaN,NaN,NaN,NaN,741.5,239.7,22.83,1.090790,NaN,NaN
2,MCI,67.5,Male,10,Hisp/Latino,White,Married,14.33,21.33,6.0,...,NaN,NaN,NaN,NaN,1501.0,153.1,13.29,NaN,NaN,NaN
3,CN,73.7,Male,16,Not Hisp/Latino,White,Married,8.67,14.67,4.0,...,NaN,NaN,NaN,NaN,547.3,337.0,33.43,1.297990,NaN,NaN
4,MCI,80.4,Female,13,Not Hisp/Latino,White,Married,18.67,25.67,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1846,CN,71.4,Male,14,Hisp/Latino,White,Married,12.00,15.00,2.0,...,1.0,1.000000,1.00,1.000000,NaN,NaN,NaN,NaN,NaN,NaN
1847,CN,65.8,Female,13,Not Hisp/Latino,White,Married,6.00,8.00,1.0,...,1.4,1.333333,1.25,1.342105,NaN,NaN,NaN,NaN,NaN,NaN
1848,MCI,76.7,Male,18,Not Hisp/Latino,White,Married,12.33,21.33,8.0,...,1.2,1.333333,1.25,1.447368,NaN,NaN,NaN,NaN,NaN,NaN
1849,CN,72.6,Male,19,Not Hisp/Latino,White,Married,6.67,8.67,0.0,...,1.0,1.333333,1.50,1.263158,NaN,NaN,NaN,NaN,NaN,NaN
1850,CN,56.5,Female,16,Not Hisp/Latino,White,Married,NaN,NaN,NaN,...,1.0,1.000000,1.00,1.000000,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
ad.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1851 entries, 0 to 1850
Data columns (total 50 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   DIAGNOSIS                 1851 non-null   object
 1   AGE                       1851 non-null   float64
 2   PTGENDER                  1851 non-null   object
 3   PTEDUCAT                  1851 non-null   int64
 4   PTETHCAT                  1851 non-null   object
 5   PTRACCAT                  1851 non-null   object
 6   PTMARRY                   1851 non-null   object
 7   ADAS11.bl                 1846 non-null   float64
 8   ADAS13.bl                 1836 non-null   float64
 9   ADASQ4.bl                 1850 non-null   float64
 10  MMSE.bl                   1851 non-null   int64
 11  RAVLT.immediate.bl        1843 non-null   float64
 12  RAVLT.learning.bl         1843 non-null   float64
 13  RAVLT.forgetting.bl       1843 non-null   float64
 14  RAVLT.perc.forgetting.bl  1837 non-null   float64
 15  LDELTOTAL.bl              1848 non-null   float64
 16  DIGITSCOR.bl              814 non-null    float64
 17  TRABSCOR.bl               1803 non-null   float64
 18  FAQ.bl                    1845 non-null   float64
 19  mPACCdigit.bl             1850 non-null   float64
 20  mPACCtrailsB.bl           1850 non-null   float64
 21  IMAGEUID.bl               1716 non-null   float64
 22  Ventricles.bl             1650 non-null   float64
 23  Hippocampus.bl            1485 non-null   float64
 24  WholeBrain.bl             1684 non-null   float64
 25  Entorhinal.bl             1461 non-null   float64
 26  Fusiform.bl               1461 non-null   float64
 27  MidTemp.bl                1461 non-null   float64
 28  ICV.bl                    1716 non-null   float64
 29  MOCA.bl                   1014 non-null   float64
 30  EcogPtMem.bl              1029 non-null   float64
 31  EcogPtLang.bl             1029 non-null   float64
 32  EcogPtVisspat.bl          1025 non-null   float64
 33  EcogPtPlan.bl             1028 non-null   float64
 34  EcogPtOrgan.bl            1005 non-null   float64
 35  EcogPtDivatt.bl           1022 non-null   float64
 36  EcogPtTotal.bl            1029 non-null   float64
 37  EcogSPMem.bl              1022 non-null   float64
 38  EcogSPLang.bl             1023 non-null   float64
 39  EcogSPVisspat.bl          1009 non-null   float64
 40  EcogSPPlan.bl             1013 non-null   float64
 41  EcogSPOrgan.bl            981 non-null    float64
 42  EcogSPDivatt.bl           1002 non-null   float64
 43  EcogSPTotal.bl            1021 non-null   float64
 44  ABETA.bl                  1215 non-null   float64
 45  TAU.bl                    1215 non-null   float64
 46  PTAU.bl                   1215 non-null   float64
 47  FDG.bl                    1301 non-null   float64
 48  PIB.bl                    20 non-null     float64
 49  AV45.bl                   891 non-null    float64
dtypes: float64(43), int64(2), object(5)
memory usage: 723.2+ KB

In [8]:
# Import label encoder 
from sklearn import preprocessing
# label_encoder object knows how to understand   word labels. 
label_encoder = preprocessing.LabelEncoder()
# Encode labels in column 'Smoking'. 
ad["Diagnosis_Ordinal"]= label_encoder.fit_transform(ad["DIAGNOSIS"]) 
print(ad.head())

  DIAGNOSIS   AGE PTGENDER  PTEDUCAT         PTETHCAT PTRACCAT  PTMARRY  \
0        CN  74.3     Male        16  Not Hisp/Latino    White  Married
1  Dementia  81.3     Male        18  Not Hisp/Latino    White  Married
2       MCI  67.5     Male        10      Hisp/Latino    White  Married
3        CN  73.7     Male        16  Not Hisp/Latino    White  Married
4       MCI  80.4   Female        13  Not Hisp/Latino    White  Married

   ADAS11.bl  ADAS13.bl  ADASQ4.bl  ...  EcogSPOrgan.bl  EcogSPDivatt.bl  \
0      10.67      18.67        5.0  ...             NaN              NaN
1      22.00      31.00        8.0  ...             NaN              NaN
2      14.33      21.33        6.0  ...             NaN              NaN
3       8.67      14.67        4.0  ...             NaN              NaN
4      18.67      25.67        7.0  ...             NaN              NaN

   EcogSPTotal.bl  ABETA.bl  TAU.bl  PTAU.bl    FDG.bl  PIB.bl  AV45.bl  \
0             NaN       NaN     NaN      NaN  1.369264     NaN      NaN
1             NaN     741.5   239.7    22.83  1.090790     NaN      NaN
2             NaN    1501.0   153.1    13.29       NaN     NaN      NaN
3             NaN     547.3   337.0    33.43  1.297990     NaN      NaN
4             NaN       NaN     NaN      NaN       NaN     NaN      NaN

   Diagnosis_Ordinal
0                  0
1                  1
2                  2
3                  0
4                  2

[5 rows x 51 columns]

In [43]:
import scipy       as sp
import scipy.stats as stats
count = ad.count()

ad_stats = pd.DataFrame(count, columns = ["Non-NaN"])

min_vals = ad.min()
ad_stats['Min'] = min_vals

max_vals = ad.max()
ad_stats['Max'] = max_vals

mean_vals = ad.mean(skipna = True)
ad_stats['Mean'] = mean_vals

median_vals = ad.median(skipna=True)
ad_stats['Median'] = median_vals

ad_mode_sci = stats.mode(ad, nan_policy='omit')
ad_stats['Mode'] = ad_mode_sci[0][0]


ad_stats

,Non-NaN,Min,Max,Mean,Median,Mode
DIAGNOSIS,1851,CN,MCI,NaN,NaN,MCI
AGE,1851,54.4,91.4,7.360394e+01,7.360000e+01,71.4
PTGENDER,1851,Female,Male,NaN,NaN,Male
PTEDUCAT,1851,4,20,1.594760e+01,1.600000e+01,16
PTETHCAT,1851,Hisp/Latino,Unknown,NaN,NaN,Not Hisp/Latino
PTRACCAT,1851,Am Indian/Alaskan,White,NaN,NaN,White
PTMARRY,1851,Divorced,Widowed,NaN,NaN,Married
ADAS11.bl,1846,0,42.67,1.079216e+01,9.330000e+00,9
ADAS13.bl,1836,0,54.67,1.680845e+01,1.500000e+01,9
ADASQ4.bl,1850,0,10,5.184324e+00,5.000000e+00,2
MMSE.bl,1851,18,30,2.727877e+01,2.800000e+01,30
RAVLT.immediate.bl,1843,0,71,3.577265e+01,3.500000e+01,27
RAVLT.learning.bl,1843,-8,12,4.277265e+00,4.000000e+00,4
RAVLT.forgetting.bl,1843,-9,15,4.300054e+00,4.000000e+00,4
RAVLT.perc.forgetting.bl,1837,-100,100,5.738251e+01,5.714286e+01,100
LDELTOTAL.bl,1848,0,23,7.358225e+00,8.000000e+00,0
DIGITSCOR.bl,814,0,80,3.703440e+01,3.800000e+01,35
TRABSCOR.bl,1803,0,300,1.194703e+02,9.300000e+01,300
FAQ.bl,1845,0,30,4.066667e+00,1.000000e+00,0
mPACCdigit.bl,1850,-23.7146,6.36174,-5.935318e+00,-4.735208e+00,-2.02719
mPACCtrailsB.bl,1850,-23.7146,5.62699,-5.632722e+00,-4.377431e+00,-18.9645
IMAGEUID.bl,1716,32003,432918,1.934016e+05,2.230495e+05,32003
Ventricles.bl,1650,5650,145115,4.028827e+04,3.527450e+04,47303
Hippocampus.bl,1485,2991,10769,6.787371e+03,6.862000e+03,5614
WholeBrain.bl,1684,669364,1.48604e+06,1.020842e+06,1.015549e+06,754507
Entorhinal.bl,1461,1426,5896,3.487671e+03,3.508000e+03,2814
Fusiform.bl,1461,8991,29950,1.730660e+04,1.726700e+04,15543
MidTemp.bl,1461,9375,32189,1.945529e+04,1.942000e+04,20620
ICV.bl,1716,1.10069e+06,2.11029e+06,1.531489e+06,1.517039e+06,1.10069e+06
MOCA.bl,1014,4,30,2.341124e+01,2.400000e+01,26
EcogPtMem.bl,1029,1,4,2.082722e+00,2.000000e+00,2
EcogPtLang.bl,1029,1,4,1.710898e+00,1.555556e+00,1
EcogPtVisspat.bl,1025,1,4,1.370541e+00,1.142857e+00,1
EcogPtPlan.bl,1028,1,4,1.384549e+00,1.200000e+00,1
EcogPtOrgan.bl,1005,1,4,1.497811e+00,1.333333e+00,1
EcogPtDivatt.bl,1022,1,4,1.780659e+00,1.750000e+00,1
EcogPtTotal.bl,1029,1,3.82051,1.660938e+00,1.538462e+00,1.35897
EcogSPMem.bl,1022,1,4,2.024938e+00,1.750000e+00,1
EcogSPLang.bl,1023,1,4,1.580347e+00,1.285714e+00,1
EcogSPVisspat.bl,1009,1,4,1.437753e+00,1.142857e+00,1
EcogSPPlan.bl,1013,1,4,1.547038e+00,1.200000e+00,1
EcogSPOrgan.bl,981,1,4,1.637802e+00,1.200000e+00,1
EcogSPDivatt.bl,1002,1,4,1.812542e+00,1.500000e+00,1
EcogSPTotal.bl,1021,1,3.94872,1.677406e+00,1.384615e+00,1
ABETA.bl,1215,199,1701,9.800850e+02,8.542000e+02,1701
TAU.bl,1215,79,1301,2.870271e+02,2.578000e+02,202.6
PTAU.bl,1215,7,121,2.764115e+01,2.415000e+01,18.85
FDG.bl,1301,0.697264,1.70717,1.233852e+00,1.245474e+00,1.10942
PIB.bl,20,1.155,2.2825,1.698375e+00,1.743750e+00,NaN
AV45.bl,891,0.838537,2.02556,1.211917e+00,1.136146e+00,NaN
Diagnosis_Ordinal,1851,0,2,1.145327e+00,1.000000e+00,2

In [117]:
# Dropping variables with not enough data
ad_df = pd.DataFrame(ad)
ad_df = ad_df.drop(columns=['EcogPtMem.bl', 'EcogPtMem.bl', 'EcogPtLang.bl', 'EcogPtVisspat.bl', 'EcogPtPlan.bl','EcogPtOrgan.bl', 'EcogPtDivatt.bl', 'EcogPtTotal.bl', 'EcogSPMem.bl',
'EcogSPLang.bl','EcogSPVisspat.bl','EcogSPPlan.bl','EcogSPOrgan.bl','EcogSPDivatt.bl','EcogSPTotal.bl', 'MOCA.bl','PIB.bl','DIGITSCOR.bl', 'AV45.bl'])
ad_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1851 entries, 0 to 1850
Data columns (total 33 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   DIAGNOSIS                 1851 non-null   object
 1   AGE                       1851 non-null   float64
 2   PTGENDER                  1851 non-null   object
 3   PTEDUCAT                  1851 non-null   int64
 4   PTETHCAT                  1851 non-null   object
 5   PTRACCAT                  1851 non-null   object
 6   PTMARRY                   1851 non-null   object
 7   ADAS11.bl                 1846 non-null   float64
 8   ADAS13.bl                 1836 non-null   float64
 9   ADASQ4.bl                 1850 non-null   float64
 10  MMSE.bl                   1851 non-null   int64
 11  RAVLT.immediate.bl        1843 non-null   float64
 12  RAVLT.learning.bl         1843 non-null   float64
 13  RAVLT.forgetting.bl       1843 non-null   float64
 14  RAVLT.perc.forgetting.bl  1837 non-null   float64
 15  LDELTOTAL.bl              1848 non-null   float64
 16  TRABSCOR.bl               1803 non-null   float64
 17  FAQ.bl                    1845 non-null   float64
 18  mPACCdigit.bl             1850 non-null   float64
 19  mPACCtrailsB.bl           1850 non-null   float64
 20  IMAGEUID.bl               1716 non-null   float64
 21  Ventricles.bl             1650 non-null   float64
 22  Hippocampus.bl            1485 non-null   float64
 23  WholeBrain.bl             1684 non-null   float64
 24  Entorhinal.bl             1461 non-null   float64
 25  Fusiform.bl               1461 non-null   float64
 26  MidTemp.bl                1461 non-null   float64
 27  ICV.bl                    1716 non-null   float64
 28  ABETA.bl                  1215 non-null   float64
 29  TAU.bl                    1215 non-null   float64
 30  PTAU.bl                   1215 non-null   float64
 31  FDG.bl                    1301 non-null   float64
 32  Diagnosis_Ordinal         1851 non-null   int32
dtypes: float64(25), int32(1), int64(2), object(5)
memory usage: 470.1+ KB

In [18]:
data_crosstab1 = pd.crosstab(ad['PTGENDER'], 
                            ad['DIAGNOSIS']) 
print(data_crosstab1)

DIAGNOSIS   CN  Dementia  MCI
PTGENDER
Female     334       157  362
Male       283       191  524

In [121]:
#replaced the 'Unknown' category with NAN and counted NANs across all the variables.

ad_df=ad_df.replace('Unknown', np.nan)
ad_df.isna().sum()

DIAGNOSIS                     0
AGE                           0
PTGENDER                      0
PTEDUCAT                      0
PTETHCAT                     12
PTRACCAT                      4
PTMARRY                       8
ADAS11.bl                     5
ADAS13.bl                    15
ADASQ4.bl                     1
MMSE.bl                       0
RAVLT.immediate.bl            8
RAVLT.learning.bl             8
RAVLT.forgetting.bl           8
RAVLT.perc.forgetting.bl     14
LDELTOTAL.bl                  3
TRABSCOR.bl                  48
FAQ.bl                        6
mPACCdigit.bl                 1
mPACCtrailsB.bl               1
IMAGEUID.bl                 135
Ventricles.bl               201
Hippocampus.bl              366
WholeBrain.bl               167
Entorhinal.bl               390
Fusiform.bl                 390
MidTemp.bl                  390
ICV.bl                      135
ABETA.bl                    636
TAU.bl                      636
PTAU.bl                     636
FDG.bl                      550
Diagnosis_Ordinal             0
dtype: int64

In [1]:
# Wrote a simple for-loop to replace the function I wrote earlier duh
# I think these tables are a lot clearer

# Perfroming chi2 tests
from scipy.stats import chi2_contingency



cols = ['PTGENDER','PTETHCAT','PTRACCAT','PTMARRY']
for i in cols:
    ct = pd.crosstab(ad_df[i], ad_df['DIAGNOSIS'], margins=True)
    stat, pvalue, dof, expected = chi2_contingency(ct)
    print(ct)
    print('Chi2 pvalue =', pvalue)

NameError: name 'pd' is not defined